version: '3.8'

services:
  frontend_tc:
    build: ./frontend
    environment:
      PORT: 3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\\.(.+)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.frontend.rule=Host(`cinephoria.fr`, `www.cinephoria.fr`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend.middlewares=www-redirect"
      - "traefik.http.services.frontend.loadbalancer.server.port=3001"
      - "traefik.http.services.frontend.loadbalancer.passHostHeader=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.frontend-http.rule=Host(`cinephoria.fr`, `www.cinephoria.fr`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https,www-redirect"
    networks:
      - rtm_network

networks:
  rtm_network:
    external: true
    name: traefik_proxy 